// Generated by dedot cli

export type InkStorageLazyMapping = {};

export type TodoAppTodo = { id: bigint; content: string; completed: boolean };

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type TodoApp = {
  todos: InkStorageLazyMapping;
  counter: InkStorageLazyMapping;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type InkEnvNoChainExtension = null;
